### ISSUE TITLE
Installation fails, also for no-build-vignettes

### ISSUE THREAD

**Issue by gcutt** [AustralianAntarcticDivision/ZooScatR#3]
> devtools::install_github("AustralianAntarcticDivision/ZooScatR", build_opts = c("--no-resave-data", "--no-manual","--no-build-vignettes"))

Downloading GitHub repo AustralianAntarcticDivision/ZooScatR@master
These packages have more recent versions available.
Which would you like to update?

1:   R6 (2.3.0 -> 2.4.0) [CRAN]

Enter one or more numbers separated by spaces, or an empty line to cancel
1: 1
R6 (2.3.0 -> 2.4.0) [CRAN]
Installing 1 packages: R6
Installing package into ‘C:/Users/g.c/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version is later:
   binary source needs_compilation
R6  2.3.0  2.4.0             FALSE

installing the source package ‘R6’

trying URL 'https://cran.rstudio.com/src/contrib/R6_2.4.0.tar.gz'
Content type 'application/x-gzip' length 31545 bytes (30 KB)
downloaded 30 KB

* installing *source* package 'R6' ...
** package 'R6' successfully unpacked and MD5 sums checked
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'R6'
    finding HTML links ... done
    R6Class                                 html  
    as.list.R6                              html  
    is.R6                                   html  
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (R6)
In R CMD INSTALL

The downloaded source packages are in
	‘C:\Users\g.c\AppData\Local\Temp\RtmpGCMGcJ\downloaded_packages’
v  checking for file 'C:\Users\g.c\AppData\Local\Temp\RtmpGCMGcJ\remotes1f403697aa6\AustralianAntarcticDivision-ZooScatR-68e7377/DESCRIPTION' ...
-  preparing 'ZooScatR': (416ms)
v  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts (364ms)
-  checking for empty or unneeded directories
-  building 'ZooScatR_0.3.0.tar.gz'
   
Installing package into ‘C:/Users/g.c/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'ZooScatR' ...
** R
Error : (converted from warning) unable to re-encode 'app.R' line 512
ERROR: unable to collate and parse R files for package 'ZooScatR'
* removing 'C:/Users/g.c/Documents/R/win-library/3.5/ZooScatR'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/g.c/AppData/Local/Temp/RtmpGCMGcJ/file1f401dc8e0/ZooScatR_0.3.0.tar.gz’ had non-zero exit status

**Comment by SvenGastauer** [comment]
For some reason some non ASCII signs ended up in the vignettes and the app.R file, which seem to cause an installation fail.
This should have been fixed now. 


On a clean Win10 install with R 3.5.2, RStudio 1.1.463, devtools 2.0.1 I managed to install the package without issues after the update with and without vignettes:

```
#no vignettes
devtools::install_github("AustralianAntarcticDivision/ZooScatR")

#with vignettes
devtools::install_github("AustralianAntarcticDivision/ZooScatR", build_opts = c("--no-manual"))
```

Alternatively, if this still fails, the package could be installed from the [source files](https://github.com/AustralianAntarcticDivision/ZooScatR/tree/master/inst/extdata/source) until we find the reason for the error.

I hope this helps.

**Comment by SvenGastauer** [comment]
Did this work for you? I was informed by a colleague that it worked on a Win7 VM as well.
If it works, I would like to close the issue here.

Thanks!

**Comment by SvenGastauer** [comment]
I assume this worked and close the issue
