### ISSUE TITLE
Vignettes

### ISSUE THREAD

**Issue by marianpena** [AustralianAntarcticDivision/ZooScatR#4]
Hi Sven. Congratulations on your R package. Looking good. Just to let you know that the vignettes weren't working for me until I included 'build_vignettes = TRUE' within the github installation code you provide. I also tried installing the zip code without any luck. I guess I needed something else installed.

Thanks!

**Comment by SvenGastauer** [comment]
Hi Marian,

 

Thanks for the feedback, I will change it in the description…That’s because of a recent change in the nomenclature of devtools, I just forgot to update the package description.

 

Hope it will be a useful package to you!

 

Cheers,

Sven
